In [3]:
#0-D ARRAY
import numpy as np
arr=np.array(42)
print(arr)


42


In [4]:
#1-D ARRAY
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
#2-D ARRAY
import numpy as numpy
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [13]:
#3-D ARRAY WITH  TWO 2-D ARRAYS
import numpy as numpy
arr =np.array ([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
#CHECK DIMENSIONS OF ARRAY
import numpy as np
a=np.array(43)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [20]:
#TO CHECK ARRAY THROUGH INDEX
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])

2


In [22]:
#SAME AS ABOVE
import numpy as ap
arr=np.array([1,2,3,4])
print(arr[0])

1


In [24]:
#GET THE 2ND AND 3RD ELEMENT INDEX AND ADD THEM
import numpy as np
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [38]:
#TO ACCESS 2-D ARRAY
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element on 1st row", arr[0,1])

2nd element on 1st row 2


In [41]:
#SLICE ELEMENTS FROM INDEX 1 TO 5 FROM FOLLOWING ARRAY
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [43]:
#IF NOT MENTIONED THE STARTING INDEX THE DEFAULT 0
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[:5])  #here start index has not been mentioned

[1 2 3 4 5]


In [44]:
#IF START AND END INDEX IS NOT MENTIONED THEN NOTHING WILL NE SLICED
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[:])

[1 2 3 4 5 6 7]


In [46]:
#SLICE ELEMENTS FROM INDEX 4 TO THE END OF THE ARRAY
import numpy as no
arr = np.array([1,2,3,4,5,6])
print(arr[4:])

[5 6]


In [47]:
#SLICE FROM BEGINNING TO INDEX 4
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print (arr[:4])

[1 2 3 4]


In [48]:
#NEGATIVE SLICING
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[-3:-1])

[6 7]


In [54]:
#USE THE STEP VALUE TO DETERMINE THE STEP OF THE SLICING 
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:3])

[2 5]


In [4]:
#RETURN EVERY OTHER ELEMENT FROM THE ENTIRE ARRAY
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [5]:
#SLICING OF 2-D ARRAY
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:4])

[6 7 8]


In [11]:
#EXERCISE 1
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,2])

6


In [12]:
#EXERCISE 2
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0:2,:])

[[1 2 3]
 [4 5 6]]


In [14]:
#EXERCISE 3
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
print (arr[:,1:3])

[[2 3]
 [5 6]
 [7 8]]
